### ISSUE TITLE
About source code of FANN Lib

### ISSUE THREAD

**Issue by sudashannon** [Counterfeiter/Q-LearningRobot#1]
Hello,
I want use the FANN Lib in the keil ide. The lib given by you can't work in the environment. So can I have the source code you transportation to compare with the FANN sourcecode to complete my project?
My email is 813475603@qq.com,plz~~~
3q

**Comment by Counterfeiter** [comment]
hello,

I did'nt touched the source code... I only compile it with compile flags to a lib (gcc).
Keil should also compile this lib without problems...
